### ISSUE TITLE
Search not given any output 

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-archive-api#8]
http://ves-pg-41:9020/search/projects?keyword=brain%20prot&pageSize=100&dateGap=%2B1YEAR

**Comment by avinash-dev** [comment]
The search is breaking because our QueryBuilder Utility was handling space separated keywords as phrases instead on performing AND condition. 
Example => Keyword: brain prot
Previous implementation returns query as:
q=accession:"brain prot" OR project_title:"brain prot" OR ..........
After fix:
q=accession:**(*brain* *prot*)** OR project_title:**(*brain* *prot*)** OR ..........**&q.op=AND**

Fixed it and gave pull request.
https://github.com/PRIDE-Archive/pride-solr-indexes/pull/12
